# user in container
ARG CONTAINER_USER=user
ARG CONTAINER_GROUP=user

ARG CONTAINER_USER_ID=1000
ARG CONTAINER_GROUP_ID=1000

# set location of workspace directory
# (temporary space within container image)
ARG WORKSPACE_ROOT_DIR="/home/${CONTAINER_USER}"

# Alpine release
ARG ALPINE_RELEASE=glibc-2.42

# ansible CLI tools versions
ARG ANSIBLE_CLI_VERSION=v2.21.3

# cert-manager CLI version
ARG CM_CTL_CLI_VERSION=v2.5.0

# Helm version
ARG HELM_CLI_VERSION=v4.2.2

# kubectl version
ARG K9S_CLI_VERSION=v0.51.0

# kops version
ARG KOPS_CLI_VERSION=v1.36.0-beta.1

# kubectl version
ARG KUBECTL_CLI_VERSION=v1.36.2

# Kustomize version
ARG KUSTOMIZE_CLI_VERSION=5.8.1

# SwarmCLI version
ARG SWARM_CLI_VERSION=v1.12.0

# Terraform version
ARG TERRAFORM_CLI_VERSION=1.16.0-alpha20260617

# OpenTofu version
ARG OPENTOFU_CLI_VERSION=1.12.5

# Terragrunt version
ARG TERRAGRUNT_CLI_VERSION=v1.1.0-rc2

# Vultr CLI version
ARG VULTR_CLI_VERSION=v3.10.0

# container as builder for preparing Vultr cloud tools
FROM frolvlad/alpine-glibc:${ALPINE_RELEASE} AS vultr-cloud-tools-builder

LABEL stage="vultr-cloud-tools-builder" \
      description="Alpine-based container builder for preparing Vultr cloud tools" \
      org.opencontainers.image.description="Alpine-based container builder for preparing Vultr cloud tools" \
      org.opencontainers.image.url=https://github.com/stefanbosak/vultr-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/vultr-cloud-tools

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# install required packages and additional applications
RUN apk add --no-cache ca-certificates bash binutils curl tar unzip

# container as builder for preparing Vultr cloud tools
FROM vultr-cloud-tools-builder AS vultr-cloud-tools-ansible-cli-builder

LABEL stage="vultr-cloud-tools-ansible-cli-builder" \
      description="Alpine-based container builder for preparing Vultr cloud tool ansible" \
      org.opencontainers.image.description="Alpine-based container builder for preparing Vultr cloud tool ansible" \
      org.opencontainers.image.url=https://github.com/stefanbosak/vultr-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/vultr-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG ANSIBLE_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# install prerequisites (uv)
RUN apk add --no-cache python3 && \
    curl -LsSf "https://astral.sh/uv/install.sh" \
      | UV_INSTALL_DIR=/usr/local/bin bash

# download and install ansible tool
RUN export UV_TOOL_BIN_DIR=/usr/local/bin && \
    export UV_TOOL_DIR=/usr/local/share/uv/tools && \
    uv tool install ansible-core==${ANSIBLE_CLI_VERSION}


# container as builder for preparing Vultr cloud tools
FROM vultr-cloud-tools-builder AS vultr-cloud-tools-cm-builder

LABEL stage="vultr-cloud-tools-cm-builder" \
      description="Alpine-based container builder for preparing Vultr cloud tool cert-manager CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing Vultr cloud tool cert-manager CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/vultr-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/vultr-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG CM_CTL_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download cert-manager
ADD "https://github.com/cert-manager/cmctl/releases/download/${CM_CTL_CLI_VERSION}/cmctl_linux_${TARGETARCH}" "${WORKSPACE_ROOT_DIR}/cmctl_linux_${TARGETARCH}"

# install cert-manager
RUN mkdir -p "/usr/local/bin/" && install -v -o root -g root -m 0755 "${WORKSPACE_ROOT_DIR}/cmctl_linux_${TARGETARCH}" "/usr/local/bin/kubectl-cert_manager"


# container as builder for preparing Vultr cloud tools
FROM vultr-cloud-tools-builder AS vultr-cloud-tools-cnpg-builder

LABEL stage="vultr-cloud-tools-cnpg-builder" \
      description="Alpine-based container builder for preparing Vultr cloud tool CNPG CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing Vultr cloud tool CNPG CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/vultr-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/vultr-cloud-tools

ARG TARGETOS
ARG TARGETARCH

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# install kubectl CNPG plugin
RUN mkdir -p "/usr/local/bin/" && \
    curl -sSfL https://github.com/cloudnative-pg/cloudnative-pg/raw/main/hack/install-cnpg-plugin.sh | \
    sh -s -- -b /usr/local/bin


# container as builder for preparing Vultr cloud tools
FROM vultr-cloud-tools-builder AS vultr-cloud-tools-helm-builder

LABEL stage="vultr-cloud-tools-helm-builder" \
      description="Alpine-based container builder for preparing Vultr cloud tool HELM CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing Vultr cloud tool HELM CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/vultr-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/vultr-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG HELM_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download HELM archive file
ADD "https://get.helm.sh/helm-${HELM_CLI_VERSION}-${TARGETOS}-${TARGETARCH}.tar.gz" "${WORKSPACE_ROOT_DIR}/"

# install HELM
RUN mkdir -p "/usr/local/bin/" && tar -xvf "${WORKSPACE_ROOT_DIR}/helm-${HELM_CLI_VERSION}-${TARGETOS}-${TARGETARCH}.tar.gz" -C "/usr/local/bin" --strip-components 1 --no-anchored "helm"


# container as builder for preparing Vultr cloud tools
FROM vultr-cloud-tools-builder AS vultr-cloud-tools-k9s-builder

LABEL stage="vultr-cloud-tools-k9s-builder" \
      description="Alpine-based container builder for preparing Vultr cloud tool k9s CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing Vultr cloud tool k9s CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/vultr-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/vultr-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG K9S_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download k9s CLI binary file
ADD "https://github.com/derailed/k9s/releases/download/${K9S_CLI_VERSION}/k9s_Linux_${TARGETARCH}.tar.gz" "${WORKSPACE_ROOT_DIR}/"

# install k9s
RUN mkdir -p "/usr/local/bin/" && tar -xvf "${WORKSPACE_ROOT_DIR}/k9s_Linux_${TARGETARCH}.tar.gz" -C "/usr/local/bin" --no-anchored "k9s"


# container as builder for preparing kops Vultr cloud tools
FROM vultr-cloud-tools-builder AS vultr-cloud-tools-kops-builder

LABEL stage="vultr-cloud-tools-kops-builder" \
      description="Alpine-based container builder for preparing Vultr cloud tool kops CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing Vultr cloud tool kops CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/vultr-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/vultr-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG KOPS_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download kubectl CLI binary file
ADD "https://github.com/kubernetes/kops/releases/download/${KOPS_CLI_VERSION}/kops-${TARGETOS}-${TARGETARCH}" "${WORKSPACE_ROOT_DIR}/"

# install kubectl
RUN mkdir -p "/usr/local/bin/" && install -v -o root -g root -m 0755 "${WORKSPACE_ROOT_DIR}/kops-${TARGETOS}-${TARGETARCH}" "/usr/local/bin/kops"


# container as builder for preparing Vultr cloud tools
FROM vultr-cloud-tools-builder AS vultr-cloud-tools-kubectl-builder

LABEL stage="vultr-cloud-tools-kubectl-builder" \
      description="Alpine-based container builder for preparing Vultr cloud tool kubectl CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing Vultr cloud tool kubectl CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/vultr-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/vultr-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG KUBECTL_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download kubectl CLI binary file
ADD "https://dl.k8s.io/release/${KUBECTL_CLI_VERSION}/bin/linux/${TARGETARCH}/kubectl" "${WORKSPACE_ROOT_DIR}/"

# install kubectl
RUN mkdir -p "/usr/local/bin/" && install -v -o root -g root -m 0755 "${WORKSPACE_ROOT_DIR}/kubectl" "/usr/local/bin/"


# container as builder for preparing Vultr cloud tools
FROM vultr-cloud-tools-builder AS vultr-cloud-tools-kustomize-builder

LABEL stage="vultr-cloud-tools-kustomize-builder" \
      description="Alpine-based container builder for preparing Vultr cloud tool kustomize CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing Vultr cloud tool kustomize CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/vultr-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/vultr-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG KUSTOMIZE_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download kustomize archive
ADD "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v${KUSTOMIZE_CLI_VERSION}/kustomize_v${KUSTOMIZE_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.tar.gz" "${WORKSPACE_ROOT_DIR}/"

# install kustomize
RUN mkdir -p "/usr/local/bin/" && tar -xvf "${WORKSPACE_ROOT_DIR}/kustomize_v${KUSTOMIZE_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.tar.gz" -C "/usr/local/bin" --no-anchored "kustomize"


# container as builder for preparing Vultr cloud tools
FROM vultr-cloud-tools-builder AS vultr-cloud-tools-swarmcli-builder

LABEL stage="vultr-cloud-tools-swarmcli-builder" \
      description="Alpine-based container builder for preparing Vultr cloud tool SwarmCLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing Vultr cloud tool SwarmCLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/vultr-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/vultr-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG SWARM_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# install SwarmCLI
RUN mkdir -p "/usr/local/bin/" && \
    curl -fsSL https://swarmcli.io/install.sh | \
    sh -s -- ce /usr/local/bin "${SWARM_CLI_VERSION}"


# container as builder for preparing Vultr cloud tools
FROM vultr-cloud-tools-builder AS vultr-cloud-tools-terraform-builder

LABEL stage="vultr-cloud-tools-terraform-builder" \
      description="Alpine-based container builder for preparing Vultr cloud tool terraform" \
      org.opencontainers.image.description="Alpine-based container builder for preparing Vultr cloud tool terraform" \
      org.opencontainers.image.url=https://github.com/stefanbosak/vultr-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/vultr-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG TERRAFORM_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download TF CLI archive file
ADD "https://releases.hashicorp.com/terraform/${TERRAFORM_CLI_VERSION}/terraform_${TERRAFORM_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.zip" "${WORKSPACE_ROOT_DIR}/"

# install TF CLI binary
RUN mkdir -p "/usr/local/bin/" && unzip "terraform_${TERRAFORM_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.zip" -d "/usr/local/bin/"


# container as builder for preparing Vultr cloud tools
FROM vultr-cloud-tools-builder AS vultr-cloud-tools-terragrunt-builder

LABEL stage="vultr-cloud-tools-terragrunt-builder" \
      description="Alpine-based container builder for preparing Vultr cloud tool terragrunt CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing Vultr cloud tool terragrunt CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/vultr-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/vultr-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG TERRAGRUNT_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download kubectl CLI binary file
ADD "https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_CLI_VERSION}/terragrunt_${TARGETOS}_${TARGETARCH}" "${WORKSPACE_ROOT_DIR}/"

# install terragrunt CLI
RUN mkdir -p "/usr/local/bin/" && install -v -o root -g root -m 0755 "${WORKSPACE_ROOT_DIR}/terragrunt_${TARGETOS}_${TARGETARCH}" "/usr/local/bin/terragrunt"


# container as builder for preparing Vultr cloud tools
FROM vultr-cloud-tools-builder AS vultr-cloud-tools-tofu-builder

LABEL stage="vultr-cloud-tools-tofu-builder" \
      description="Alpine-based container builder for preparing Vultr cloud tool OpenTofu" \
      org.opencontainers.image.description="Alpine-based container builder for preparing Vultr cloud tool OpenTofu" \
      org.opencontainers.image.url=https://github.com/stefanbosak/vultr-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/vultr-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG OPENTOFU_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download OpenTofu CLI archive file (https://github.com/opentofu/opentofu/)
ADD "https://github.com/opentofu/opentofu/releases/download/v${OPENTOFU_CLI_VERSION}/tofu_${OPENTOFU_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.zip" "${WORKSPACE_ROOT_DIR}/"

# install OpenTofu CLI binary
RUN mkdir -p "/usr/local/bin/" && unzip "tofu_${OPENTOFU_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.zip" -d "/usr/local/bin/"


# container as builder for preparing Vultr cloud tools
FROM vultr-cloud-tools-builder AS vultr-cloud-tools-vultr-cli-builder

LABEL stage="vultr-cloud-tools-vultr-cli-builder" \
      description="Alpine-based container builder for preparing Vultr cloud tool Vultr CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing Vultr cloud tool Vultr CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/vultr-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/vultr-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG VULTR_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download Vultr CLI archive file (https://github.com/vultr/vultr-cli)
ADD "https://github.com/vultr/vultr-cli/releases/download/${VULTR_CLI_VERSION}/vultr-cli_${VULTR_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.tar.gz" "${WORKSPACE_ROOT_DIR}/"

# install Vultr CLI
RUN mkdir -p "/usr/local/bin/" && tar -xvf "${WORKSPACE_ROOT_DIR}/vultr-cli_${VULTR_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.tar.gz" -C "/usr/local/bin" --no-anchored "vultr-cli"


FROM scratch AS vultr-cloud-tools-binaries-aggregator

# transfer tools from builders
COPY --from=vultr-cloud-tools-ansible-cli-builder "/usr/local/bin" "/usr/local/bin"
COPY --from=vultr-cloud-tools-ansible-cli-builder "/usr/local/share/uv/tools" "/usr/local/share/uv/tools"
COPY --from=vultr-cloud-tools-cm-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=vultr-cloud-tools-cnpg-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=vultr-cloud-tools-helm-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=vultr-cloud-tools-k9s-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=vultr-cloud-tools-kops-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=vultr-cloud-tools-kubectl-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=vultr-cloud-tools-kustomize-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=vultr-cloud-tools-swarmcli-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=vultr-cloud-tools-terraform-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=vultr-cloud-tools-terragrunt-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=vultr-cloud-tools-tofu-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=vultr-cloud-tools-vultr-cli-builder "/usr/local/bin/" "/usr/local/bin/"


# container as final image for providing Vultr cloud tools
FROM frolvlad/alpine-glibc:${ALPINE_RELEASE} AS vultr-cloud-tools-image

LABEL stage="vultr-cloud-tools-image" \
      description="Alpine-based container with Vultr cloud tools" \
      org.opencontainers.image.description="Alpine-based container with Vultr cloud tools" \
      org.opencontainers.image.url=https://github.com/stefanbosak/vultr-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/vultr-cloud-tools

ARG TARGETOS
ARG TARGETARCH

# user in container
ARG CONTAINER_USER
ARG CONTAINER_GROUP

ARG CONTAINER_USER_ID
ARG CONTAINER_GROUP_ID

ARG HOME_ROOT_DIR="/home/${CONTAINER_USER}"

WORKDIR "${HOME_ROOT_DIR}"

RUN mkdir -p "/usr/local/bin/" && \
    apk add --no-cache \
      bash \
      bash-completion \
      bc \
      bind-tools \
      ca-certificates \
      curl \
      docker \
      docker-cli-buildx \
      docker-cli-compose \
      git \
      gnupg \
      gzip \
      iproute2 \
      iputils \
      jq \
      kmod \
      lsof \
      openssh-client \
      pigz \
      procps \
      psmisc \
      py3-argcomplete \
      py3-virtualenv \
      python3 \
      ripgrep \
      rsync \
      shadow \
      socat \
      unzip \
      tar \
      wget \
      whois

# copy tools from aggregator
COPY --from=vultr-cloud-tools-binaries-aggregator / /

# setup user and group
RUN if getent group "${CONTAINER_GROUP_ID}" > /dev/null; then \
      _existing_group="$(getent group "${CONTAINER_GROUP_ID}" | cut -d: -f1)"; \
      if [ "${_existing_group}" != "${CONTAINER_GROUP}" ]; then \
        groupmod -n "${CONTAINER_GROUP}" "${_existing_group}"; \
      fi; \
    else \
      groupadd --gid "${CONTAINER_GROUP_ID}" "${CONTAINER_GROUP}"; \
    fi \
    && if getent passwd "${CONTAINER_USER_ID}" > /dev/null; then \
         _existing_user="$(getent passwd "${CONTAINER_USER_ID}" | cut -d: -f1)"; \
         if [ "${_existing_user}" != "${CONTAINER_USER}" ]; then \
           if [ -d "/home/${_existing_user}" ]; then \
             mv "/home/${_existing_user}" "/home/${CONTAINER_USER}"; \
           fi; \
           usermod -d "${HOME_ROOT_DIR}" -l "${CONTAINER_USER}" "${_existing_user}"; \
         fi; \
       else \
         useradd \
           --uid "${CONTAINER_USER_ID}" \
           --gid "${CONTAINER_GROUP_ID}" \
           --groups "${CONTAINER_GROUP}" \
           -M -d "${HOME_ROOT_DIR}" \
           -s /bin/bash \
           "${CONTAINER_USER}"; \
       fi \
    && chown -R "${CONTAINER_USER}:${CONTAINER_GROUP}" "${HOME_ROOT_DIR}" \
    && usermod -aG docker "${CONTAINER_USER}" && \
# enable tools completions (required to run given tool to generate completion file content)
    ln -s /usr/local/bin/kubectl-cert_manager /usr/local/bin/cmctl && \
    cmctl completion bash > /usr/share/bash-completion/completions/cmctl && \
    ln -s /usr/local/bin/kubectl-cnpg /usr/local/bin/cnpgctl && \
    cnpgctl completion bash > /usr/share/bash-completion/completions/cnpgctl && \
    sed -i 's/kubectl-cnpg/cnpgctl/g' /usr/share/bash-completion/completions/cnpgctl && \
    helm completion bash > "/usr/share/bash-completion/completions/helm" && \
    k9s completion bash > "/usr/share/bash-completion/completions/k9s" && \
    kops completion bash > "/usr/share/bash-completion/completions/kops" && \
    kubectl completion bash > "/usr/share/bash-completion/completions/kubectl" && \
    cp "/usr/share/bash-completion/completions/kubectl" "/usr/share/bash-completion/completions/k" && \
    sed -i 's/kubectl/k/g' "/usr/share/bash-completion/completions/k" && \
    ln -s /usr/local/bin/kubectl /usr/local/bin/k && \
    kustomize completion bash > "/usr/share/bash-completion/completions/kustomize" && \
    vultr-cli completion bash > "/usr/share/bash-completion/completions/vultr-cli" && \
    echo "complete -C terraform terraform" > "/usr/share/bash-completion/completions/terraform" && \
    echo "complete -C terragrunt terragrunt" > "/usr/share/bash-completion/completions/terragrunt" && \
    echo "complete -C tofu tofu" > "/usr/share/bash-completion/completions/tofu" && \
    activate-global-python-argcomplete

# container user and group
USER "${CONTAINER_USER}:${CONTAINER_GROUP}"

WORKDIR "${HOME_ROOT_DIR}"

RUN cp /etc/skel/.bashrc /etc/skel/.profile "${HOME_ROOT_DIR}"

# open shell
CMD ["bash"]
